#include "../Overlay.h"
#include "../OpticalFlow.h"
#include "../mcp/McpEditorTools.h"
#include <QElapsedTimer>
#include <QJsonArray>
#include <QPainter>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <random>
#include <vector>

namespace {
bool sameBits(const QImage &a, const QImage &b)
{
    return a.size() == b.size() && a.format() == b.format()
        && a.bytesPerLine() == b.bytesPerLine() && a.sizeInBytes() == b.sizeInBytes()
        && std::memcmp(a.constBits(), b.constBits(), size_t(a.sizeInBytes())) == 0;
}
QImage noise(int w, int h, unsigned seed, int base = 0, int range = 256)
{
    std::mt19937 rng(seed);
    QImage image(w, h, QImage::Format_RGB32);
    for (int y = 0; y < h; ++y) {
        auto *row = reinterpret_cast<QRgb *>(image.scanLine(y));
        for (int x = 0; x < w; ++x) {
            const int v = base + int(rng() % unsigned(range));
            row[x] = qRgb(v, v, v);
        }
    }
    return image;
}
// Normalized correlation of an interior patch avoids the occlusion boundary.
// x is the square's left edge, so the expected halfway position is 60.
double correlation(const QImage &image, const QImage &texture, int x)
{
    double sumA = 0, sumB = 0, aa = 0, bb = 0, ab = 0;
    constexpr int n = 24 * 24;
    for (int y = 12; y < 36; ++y) {
        for (int dx = 12; dx < 36; ++dx) {
            const double a = qRed(image.pixel(x + dx, 32 + y));
            const double b = qRed(texture.pixel(dx, y));
            sumA += a; sumB += b; aa += a * a; bb += b * b; ab += a * b;
        }
    }
    const double denom = std::sqrt(std::max(0.0, (aa - sumA * sumA / n) * (bb - sumB * sumB / n)));
    return denom > 0 ? (ab - sumA * sumB / n) / denom : 0;
}
std::vector<int> peaks(const QImage &image, const QImage &texture)
{
    std::vector<int> result;
    for (int x = 1; x < 127; ++x) {
        const double c = correlation(image, texture, x);
        if (c > 0.35 && c > correlation(image, texture, x - 1)
                     && c >= correlation(image, texture, x + 1)) result.push_back(x);
    }
    return result;
}
}

int runMorphCutSelftest()
{
    int passed = 0, failed = 0;
    const auto check = [&](int gate, bool ok) {
        std::fprintf(stderr, "%s G%d\n", ok ? "PASS" : "FAIL", gate);
        ok ? ++passed : ++failed;
    };
    const QImage texture = noise(64, 64, 202, 64, 192);
    QImage a = noise(192, 128, 100, 0, 48);
    QImage b = a.copy();
    { QPainter painter(&a); painter.drawImage(40, 32, texture); }
    { QPainter painter(&b); painter.drawImage(80, 32, texture); }
    const auto morph = [](const QImage &u, const QImage &v, double t = 0.5) {
        return OverlayRenderer::applyTransition(u, v, TransitionType::MorphCut, t);
    };
    OverlayRenderer::clearMorphCutCacheForTest();
    const QImage middle = morph(a, b);
    const auto mp = peaks(middle, texture);
    const auto cp = peaks(OverlayRenderer::applyTransition(a, b, TransitionType::CrossDissolve, 0.5), texture);
    check(1, mp.size() == 1 && std::abs(mp.front() - 60) <= 10
        && cp.size() == 2 && std::abs(cp[0] - 40) <= 2 && std::abs(cp[1] - 80) <= 2);
    std::fprintf(stderr, "correlation peaks: morph");
    for (int x : mp) std::fprintf(stderr, " %d", x);
    std::fprintf(stderr, "; dissolve");
    for (int x : cp) std::fprintf(stderr, " %d", x);
    std::fprintf(stderr, "\n");

    bool endpoints = sameBits(morph(a, b, 0), a) && sameBits(morph(a, b, 1), b);
    OverlayRenderer::clearMorphCutCacheForTest();
    endpoints &= sameBits(morph(a, b, 0), a) && sameBits(morph(a, b, 1), b);
    QImage odd(17, 9, QImage::Format_RGB888);
    std::memset(odd.bits(), 0xa5, size_t(odd.sizeInBytes()));
    endpoints &= sameBits(morph(odd, b, -0.1), odd) && sameBits(morph(odd, b, 1.1), b)
        && morph(QImage(), b, 0).isNull() && morph(a, QImage(), 1).isNull();
    check(2, endpoints);
    const QImage uncached = morph(a, b);
    const QImage cached = morph(a, b);
    OverlayRenderer::clearMorphCutCacheForTest();
    check(3, sameBits(middle, uncached) && sameBits(uncached, cached) && sameBits(cached, morph(a, b)));

    // Read the actual public MCP schema generated by transitionTypeNames().
    // Registration constructs no MainWindow/Timeline and needs no QApplication.
    mcp::McpToolRegistry registry;
    mcp::McpEditorTools editor(nullptr, &registry);
    editor.registerWriteTools();
    QJsonArray names;
    for (const auto &value : registry.listToolsJson()) {
        const auto tool = value.toObject();
        if (tool.value("name").toString() == QStringLiteral("set_transition"))
            names = tool.value("inputSchema").toObject().value("properties").toObject()
                .value("type").toObject().value("enum").toArray();
    }
    const char *expected[] = {
        "None", "FadeIn", "FadeOut", "CrossDissolve", "WipeLeft", "WipeRight", "WipeUp", "WipeDown",
        "SlideLeft", "SlideRight", "SlideUp", "SlideDown", "DipToBlack", "DipToWhite", "IrisRound", "IrisBox",
        "ClockWipe", "BarnDoorHorizontal", "BarnDoorVertical", "PushLeft", "PushRight", "PushUp", "PushDown",
        "CrossZoom", "FilmDissolve", "SpinCW", "SpinCCW", "DitherDissolve", "IrisRoundClose", "IrisBoxClose",
        "BarnDoorHClose", "BarnDoorVClose", "ClockWipeCCW", "WhipPanLeft", "WhipPanRight", "Glitch", "LightLeak",
        "FlipHorizontal", "FlipVertical", "LensFlare", "FilmBurn", "Pixelate", "BlurDissolve", "CameraShake",
        "ColorChannelShift", "MorphCut"
    };
    bool ordinals = static_cast<int>(TransitionType::None) == 0
        && static_cast<int>(TransitionType::CrossDissolve) == 3
        && static_cast<int>(TransitionType::LightLeak) == 36
        && static_cast<int>(TransitionType::FlipHorizontal) == 37
        && static_cast<int>(TransitionType::ColorChannelShift) == 44
        && static_cast<int>(TransitionType::MorphCut) == 45
        && names.size() == static_cast<int>(TransitionType::MorphCut) + 1
        && isOverlapTransition(TransitionType::MorphCut)
        && Transition::typeName(TransitionType::MorphCut) == QStringLiteral("Morph Cut");
    for (int i = 0; i < 46; ++i)
        ordinals &= names.size() > i && names.at(i).toString() == QLatin1String(expected[i]);
    check(4, ordinals);

    const QImage hdA = noise(1920, 1080, 5);
    const QImage hdB = noise(1920, 1080, 6);
    const QImage smallA = hdA.scaled(480, 480, Qt::KeepAspectRatio, Qt::SmoothTransformation);
    const QImage smallB = hdB.scaled(smallA.size(), Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
    opticalflow::FlowParams params;
    params.levels = 3; params.blockSize = 16; params.searchRange = 16; params.smooth = true;
    QElapsedTimer timer;
    timer.start();
    const auto flow = opticalflow::estimateFlow(smallA, smallB, params);
    const qint64 elapsed = timer.elapsed();
    check(5, !flow.v.isEmpty() && elapsed <= 5000);
    std::fprintf(stderr, "estimateFlow: %lld ms\n", static_cast<long long>(elapsed));

    const QImage otherA = noise(192, 128, 8);
    const QImage otherB = noise(192, 128, 9);
    const QImage otherWarm = morph(otherA, otherB);
    OverlayRenderer::clearMorphCutCacheForTest();
    const QImage otherCold = morph(otherA, otherB);
    bool isolated = !sameBits(middle, otherWarm) && sameBits(otherWarm, otherCold);
    // Exercise eviction as well as same-sized content keys.
    for (unsigned i = 0; i < 5; ++i) morph(noise(192, 128, 20 + i), otherB);
    isolated &= sameBits(otherCold, morph(otherA, otherB)) && sameBits(middle, morph(a, b));
    check(6, isolated);
    OverlayRenderer::clearMorphCutCacheForTest();
    std::fprintf(stderr, "summary: %d PASS, %d FAIL\n", passed, failed);
    return failed;
}
